# Generated by Django 3.2.9 on 2021-11-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='mood',
            field=models.CharField(default='Alegre', max_length=200),
        ),
    ]
