# Generated by Django 3.2.9 on 2021-11-15 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20211115_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 18, 59, 30, 898181), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
